DEBUG = True

SQLALCHEMY_DATABASE_URI = 'POTATO'
SQLALCHEMY_TRACK_MODIFICATIONS = False

COMMIT_ID = 'TESTING'

BEEVENUE_ALLOWED_CORS_ORIGINS = ['http://localhost:*']

BEEVENUE_THUMBNAIL_SIZES = {
    's': 240,
    'l': 600
}

SECRET_KEY = "TESTING_ONLY"
