"""empty message

Revision ID: 0d24dab26f2b
Revises: 
Create Date: 2020-02-16 07:57:17.641910

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0d24dab26f2b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medium",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hash", sa.String(length=32), nullable=False),
        sa.Column("mime_type", sa.String(length=256), nullable=False),
        sa.Column(
            "aspect_ratio", sa.Numeric(precision=4, scale=2), nullable=True
        ),
        sa.Column(
            "rating", sa.Enum("e", "s", "q", "u", name="Rating"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash"),
    )
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tag"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=256), nullable=False),
        sa.Column("hash", sa.String(length=256), nullable=False),
        sa.Column("role", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "medium_tag",
        sa.Column("medium_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["medium_id"], ["medium.id"],),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"],),
        sa.PrimaryKeyConstraint("medium_id", "tag_id"),
    )
    op.create_table(
        "tagAlias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alias"),
    )
    op.create_table(
        "tagImplication",
        sa.Column("implying_tag_id", sa.Integer(), nullable=False),
        sa.Column("implied_tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["implied_tag_id"], ["tag.id"],),
        sa.ForeignKeyConstraint(["implying_tag_id"], ["tag.id"],),
        sa.PrimaryKeyConstraint("implying_tag_id", "implied_tag_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tagImplication")
    op.drop_table("tagAlias")
    op.drop_table("medium_tag")
    op.drop_table("user")
    op.drop_table("tag")
    op.drop_table("medium")
    # ### end Alembic commands ###
