"""empty message

Revision ID: 16245cfe3d4b
Revises: 0d24dab26f2b
Create Date: 2020-02-20 19:50:42.920972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "16245cfe3d4b"
down_revision = "0d24dab26f2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tag",
        sa.Column(
            "rating", sa.Enum("e", "s", "q", "u", name="Rating"), nullable=True
        ),
    )

    op.execute("UPDATE tag SET rating = 'u'")

    op.alter_column("tag", "rating", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tag", "rating")
    # ### end Alembic commands ###
