"""empty message

Revision ID: 7d21ba25a4b2
Revises: 16245cfe3d4b
Create Date: 2020-02-22 14:46:50.266690

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "7d21ba25a4b2"
down_revision = "16245cfe3d4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "medium", sa.Column("tiny_thumbnail", sa.LargeBinary(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("medium", "tiny_thumbnail")
    # ### end Alembic commands ###
