"""empty message

Revision ID: a19c1d2e5764
Revises: 7d21ba25a4b2
Create Date: 2020-10-20 08:55:57.686995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a19c1d2e5764"
down_revision = "7d21ba25a4b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_medium_tag_medium_id"),
        "medium_tag",
        ["medium_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medium_tag_tag_id"), "medium_tag", ["tag_id"], unique=False
    )
    op.create_index(
        op.f("ix_tagAlias_tag_id"), "tagAlias", ["tag_id"], unique=False
    )
    op.create_index(
        op.f("ix_tagImplication_implied_tag_id"),
        "tagImplication",
        ["implied_tag_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tagImplication_implying_tag_id"),
        "tagImplication",
        ["implying_tag_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tagImplication_implying_tag_id"), table_name="tagImplication"
    )
    op.drop_index(
        op.f("ix_tagImplication_implied_tag_id"), table_name="tagImplication"
    )
    op.drop_index(op.f("ix_tagAlias_tag_id"), table_name="tagAlias")
    op.drop_index(op.f("ix_medium_tag_tag_id"), table_name="medium_tag")
    op.drop_index(op.f("ix_medium_tag_medium_id"), table_name="medium_tag")
    # ### end Alembic commands ###
