name: Black

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Install black
        run: pip install black
      - name: Run black
        run: black . # Should respect pyproject.toml automatically
      - name: Create PR (if necessary)
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Black autoformat changes"
          title: "Black autoformat changes"
          author: "PRBot <prbot@prat.ch>"
          body: Please merge these autoformatting changes.
