name: Run isort
on:
  - push

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: jamescurtin/isort-action@master
        with:
          configuration: "."
          requirementsFiles: "requirements.txt requirements.cionly.txt requirements.linuxonly.txt"
      - name: Create PR (if necessary)
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "isort autoformat changes"
          title: "isort autoformat changes"
          author: "PRBot <prbot@prat.ch>"
          body: Please merge these autoformatting changes.
