name: Black

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1
        with:
          args: ". -l 80"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Black formatting"
          title: "Black autoformat"
          author: "PRBot <prbot@prat.ch>"
          body: Please merge these autoformatting changes
