name: Mypy
on:
  - push

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements.linuxonly.txt -r requirements.cionly.txt mypy
      - name: Run mypy
        run: mypy .
